# Generated by Django 4.1.9 on 2024-06-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Dname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
