# Generated by Django 4.1.9 on 2024-06-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_department_dname_alter_student_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Did',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
